### ISSUE TITLE
Remove the code from reading the stdin: "enter pressed, try to login"

### ISSUE THREAD

**Issue by huan** [wechaty/puppet-oicq#8]
https://github.com/wechaty/wechaty-puppet-oicq/blob/fa8126d57675af970e56b29cf7ef0324d34e9411/src/puppet-oicq.ts#L94-L98

The puppet should not depend on the stdin input, because it will be mostly running under the daemon mode, which is no stdin at all.

**Comment by anaivebird** [comment]
Currently, the problem is after user scans the qr code and press login on their phone, oicq puppet could not monitor the QR code scanned event from protocolscanned event from Tencent server). 

Due to oicq didn't implement monitoring user scanning QR code event part, we should received a ender pressed from terminal(or wechaty should use call some function) to notice puppet QR code has been scanned and oicq should log in.)

And the perfect restart problem https://github.com/wechaty/wechaty-puppet-oicq/issues/10#issue-1012798249 should also be attributed to the QR code terminal pressing waiting problem.

**Comment by anaivebird** [comment]
Current workaround is: after QR code show, bot will wait 20 seconds.  If user scan on phone in 20 seconds, bot will login successfully, otherwise a new QR code will be shown.(due to timeout set by QQ)

every 20 seconds:
`18:47:13 VERB check if QR code is scanned (try to login) if not scanned, new QR code will be shown `

**Comment by huan** [comment]
This workaround is acceptable because it resolves a blocker defect problem in the previous version.

Please go ahead to implemented it, and I hope we can find a better way to improve it in the future.
